spring.application.name=Cart service
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8100
grpc.server.port=7100

kafka.topic.order-status-updated=order-status-updated
kafka.topic.variant-price-changed=variant-price-changed
kafka.topic.variant-stock-changed=variant-stock-changed
kafka.topic.variant-deleted=variant-deleted
kafka.topic.product-deleted=product-deleted
kafka.topic.variant-image-updated=variant-image-updated

