version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-cart
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/postgres-cart/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: